var screen = 'home';
var locale = 'ru';
var weight = 100;
var reps = 8;
var rir = 2;
var setStarted = false;
var completedSets = 1;
var restSeconds = 90;

function text() {
  if (locale === 'en') {
    return {
      activeWorkout: 'Active workout',
      lastWorkout: 'Last workout',
      diagnostics: 'Diagnostics',
      connected: 'Preview connected',
      synced: 'Synced',
      open: 'Open',
      startSet: 'Start set',
      completeSet: 'Complete set',
      pause: 'Pause',
      resume: 'Resume',
      back: 'Back'
    };
  }
  return {
    activeWorkout: 'Активная тренировка',
    lastWorkout: 'Последняя тренировка',
    diagnostics: 'Диагностика',
    connected: 'Preview подключён',
    synced: 'Синхронизировано',
    open: 'Открыть',
    startSet: 'Начать подход',
    completeSet: 'Завершить подход',
    pause: 'Пауза',
    resume: 'Продолжить',
    back: 'Назад'
  };
}

function render() {
  var labels = text();
  return {
    showHome: screen === 'home',
    showWorkout: screen === 'workout',
    showSetEntry: screen === 'set',
    showRest: screen === 'rest',
    showExerciseSummary: screen === 'exerciseSummary',
    showWorkoutSummary: screen === 'workoutSummary',
    showDiagnostics: screen === 'diagnostics',
    hasWorkout: true,
    noWorkout: false,
    hasLastWorkout: true,
    noLastWorkout: false,
    hasLastError: false,
    noLastError: true,
    showStartSet: !setStarted,
    showCompleteSet: setStarted,
    showRemoteActiveSet: false,
    showExerciseNavigation: !setStarted && screen !== 'rest',
    showPauseButton: true,
    showLastSetActions: completedSets > 0,
    connectionLabel: labels.connected,
    syncStatusLabel: labels.synced,
    pendingCount: '0',
    languageButton: locale === 'ru' ? 'EN' : 'RU',
    activeWorkoutLabel: labels.activeWorkout,
    lastWorkoutLabel: labels.lastWorkout,
    noLastWorkoutLabel: locale === 'ru' ? 'Истории пока нет' : 'No history yet',
    exerciseSummaryLabel: locale === 'ru' ? 'Итог упражнения' : 'Exercise summary',
    workoutSummaryLabel: locale === 'ru' ? 'Итог тренировки' : 'Workout summary',
    diagnosticsLabel: labels.diagnostics,
    phoneConnectionLabel: locale === 'ru' ? 'Телефон' : 'Phone',
    currentHrLabel: locale === 'ru' ? 'Пульс' : 'Heart rate',
    currentHeartRate: '128 BPM',
    noWorkoutLabel: locale === 'ru' ? 'Нет активной тренировки' : 'No active workout',
    waitingLabel: locale === 'ru' ? 'Ожидание' : 'Waiting',
    openLabel: labels.open,
    durationLabel: locale === 'ru' ? 'Длительность' : 'Duration',
    pingLabel: 'Ping',
    syncLabel: locale === 'ru' ? 'Синхронизация' : 'Sync',
    pendingLabel: locale === 'ru' ? 'В очереди' : 'Pending',
    protocolLabel: locale === 'ru' ? 'Протокол' : 'Protocol',
    conflictsLabel: locale === 'ru' ? 'Конфликты' : 'Conflicts',
    lastSyncLabel: locale === 'ru' ? 'Последняя синхронизация' : 'Last sync',
    lastErrorLabel: locale === 'ru' ? 'Последняя ошибка' : 'Last error',
    noErrorsLabel: locale === 'ru' ? 'Ошибок нет' : 'No errors',
    backLabel: labels.back,
    setLabel: locale === 'ru' ? 'Подход' : 'Set',
    targetLabel: locale === 'ru' ? 'План' : 'Target',
    previousLabel: locale === 'ru' ? 'Назад' : 'Previous',
    nextLabel: locale === 'ru' ? 'Далее' : 'Next',
    editSetLabel: locale === 'ru' ? 'Редактировать подход' : 'Edit set',
    startSetLabel: labels.startSet,
    completeSetLabel: labels.completeSet,
    correctLastSetLabel: locale === 'ru' ? 'Исправить последний' : 'Correct last set',
    deleteLastSetLabel: locale === 'ru' ? 'Удалить подход' : 'Delete set',
    activeSetOnPhoneLabel: locale === 'ru' ? 'Подход идёт на телефоне' : 'Set active on phone',
    weightLabel: locale === 'ru' ? 'Вес' : 'Weight',
    repsLabel: locale === 'ru' ? 'Повторения' : 'Reps',
    rirLabel: 'RIR',
    restLabel: locale === 'ru' ? 'Отдых' : 'Rest',
    restMinimumLabel: locale === 'ru' ? 'Минимум' : 'Minimum',
    restAverageLabel: locale === 'ru' ? 'Средний' : 'Average',
    restAt30Label: '30 сек',
    restAt60Label: '60 сек',
    skipLabel: locale === 'ru' ? 'Пропустить' : 'Skip',
    add15Label: '+15 сек',
    add30Label: '+30 сек',
    pauseResumeLabel: labels.pause,
    exerciseName: locale === 'ru' ? 'Приседания со штангой' : 'Barbell squat',
    setProgress: String(completedSets + 1) + ' / 4',
    targetSummary: '8 повторений · RIR 2',
    elapsed: '32:18',
    setElapsed: setStarted ? '00:24' : '00:00',
    restCountdown: '01:' + ('0' + String(restSeconds % 60)).slice(-2),
    restMinimum: '118 BPM',
    restAverage: '126 BPM',
    restAt30: '124 BPM',
    restAt60: '119 BPM',
    draftWeight: String(weight),
    draftReps: String(reps),
    draftRir: String(rir),
    lastWorkoutSets: locale === 'ru' ? 'Завершено подходов: 18' : 'Finished sets: 18',
    lastWorkoutDuration: locale === 'ru' ? 'Длительность: 58:42' : 'Duration: 58:42',
    lastWorkoutFinishedAt: '2026-07-14 19:10',
    summaryExerciseName: locale === 'ru' ? 'Приседания со штангой' : 'Barbell squat',
    summarySetCount: '4',
    summaryVolume: '3200 kg',
    summaryAverageRir: '1.8',
    summaryMaximumHeartRate: '158 BPM',
    summaryAverageHeartRate: '141 BPM',
    summaryRecovery60: '-22 BPM',
    workoutExerciseCount: '6',
    workoutSetCount: '18',
    workoutVolume: '8240 kg',
    workoutAverageRir: '1.7',
    workoutMaximumHeartRate: '164 BPM',
    workoutAverageHeartRate: '138 BPM',
    workoutAverageRestHeartRate: '123 BPM',
    workoutRecovery60: '-20 BPM',
    workoutSummaryDuration: '58:42',
    finishedSetsLabel: locale === 'ru' ? 'Подходы' : 'Sets',
    exerciseCountLabel: locale === 'ru' ? 'Упражнения' : 'Exercises',
    totalVolumeLabel: locale === 'ru' ? 'Объём' : 'Volume',
    averageRirLabel: locale === 'ru' ? 'Средний RIR' : 'Average RIR',
    maximumHrLabel: locale === 'ru' ? 'Максимальный пульс' : 'Maximum HR',
    averageHrLabel: locale === 'ru' ? 'Средний пульс' : 'Average HR',
    averageRestHrLabel: locale === 'ru' ? 'Пульс отдыха' : 'Rest HR',
    recovery60Label: locale === 'ru' ? 'Восстановление 60 сек' : 'Recovery 60 sec',
    summarySyncStatus: labels.synced + ' · 0',
    diagnosticConnection: labels.connected,
    diagnosticSync: labels.synced,
    diagnosticProtocol: '1.0',
    diagnosticPending: '0',
    diagnosticConflicts: '0',
    diagnosticLastSync: 'только что',
    diagnosticLastError: locale === 'ru' ? 'Ошибок нет' : 'No errors'
  };
}

function refresh(page) {
  Object.assign(page, render());
}

export default {
  data: render(),
  toggleLanguage() { locale = locale === 'ru' ? 'en' : 'ru'; refresh(this); },
  openWorkout() { screen = 'workout'; refresh(this); },
  openLastWorkout() { screen = 'workoutSummary'; refresh(this); },
  openExerciseSummary() { screen = 'exerciseSummary'; refresh(this); },
  openWorkoutSummary() { screen = 'workoutSummary'; refresh(this); },
  openDiagnostics() { screen = 'diagnostics'; refresh(this); },
  closeSummary() { screen = 'home'; refresh(this); },
  previousSummaryExercise() { refresh(this); },
  nextSummaryExercise() { refresh(this); },
  goHome() { screen = 'home'; refresh(this); },
  openSetEntry() { screen = 'set'; refresh(this); },
  closeSetEntry() { screen = 'workout'; refresh(this); },
  sendPing() { refresh(this); },
  requestState() { refresh(this); },
  previousExercise() { refresh(this); },
  nextExercise() { refresh(this); },
  startSet() { setStarted = true; refresh(this); },
  completeSet() { setStarted = false; completedSets += 1; screen = 'rest'; refresh(this); },
  correctLastSet() { refresh(this); },
  deleteLastSet() { completedSets = Math.max(0, completedSets - 1); refresh(this); },
  skipRest() { screen = 'workout'; refresh(this); },
  add15Seconds() { restSeconds += 15; refresh(this); },
  add30Seconds() { restSeconds += 30; refresh(this); },
  togglePause() { refresh(this); },
  startNextSet() { screen = 'set'; setStarted = true; refresh(this); },
  weightDown() { weight = Math.max(0, weight - 2.5); refresh(this); },
  weightUp() { weight = Math.min(500, weight + 2.5); refresh(this); },
  repsDown() { reps = Math.max(1, reps - 1); refresh(this); },
  repsUp() { reps = Math.min(100, reps + 1); refresh(this); },
  rirDown() { rir = Math.max(0, rir - 1); refresh(this); },
  rirUp() { rir = Math.min(5, rir + 1); refresh(this); }
};
