-- AlterTable
ALTER TABLE "GymExerciseConfig" ADD COLUMN "dumbbellWeights" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN "plateWeights" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[],
ADD COLUMN "barWeights" DOUBLE PRECISION[] NOT NULL DEFAULT ARRAY[]::DOUBLE PRECISION[];